### ISSUE TITLE
TLogFileProvider.WriteToStream AutoFlush check

### ISSUE THREAD

**Issue by avpnvpn** [exilon/QuickLogger#113]
```
TLogFileProvider.WriteToStream:
  if not fAutoFlush then fLogWriter.Flush;
```
Should it be this?
`
  if fAutoFlush then fLogWriter.Flush;
`

**Comment by exilon** [comment]
No, only for file provider.
AutoFlush = True means writes to file are controlled by OS,
Autoflush = False means writes to disk occurs on every new log line (more agressive)
If your application is critical and you don't want to lost any log line when your app crashes and log is not flushed fully to disk, you must set it to False. But I recommend use AutoFlush because is less agressive and better performance.
